;; bootstrapping init.el
(package-initialize)
;; (add-to-list 'package-archives '("marmalade" . "http://marmalade-repo.org/packages/"))
(add-to-list 'package-archives '("melpa" . "http://melpa.milkbox.net/packages/"))
(add-to-list 'package-archives '("melpa-stable" . "http://melpa-stable.milkbox.net/packages/") t)

(setq package-pinned-packages
      '((ac-cider . "melpa-stable")
	(auctex . "gnu")
	(auto-complete . "melpa-stable")
	(cider . "melpa-stable")
	(company . "gnu")
	(company-ghc . "melpa-stable")
	(clojure-mode . "melpa-stable")
	(flycheck . "melpa-stable")
	(flycheck-haskell . "melpa-stable")
	(ghc . "melpa-stable")
	(haskell-mode . "melpa-stable")
	(rainbow-delimiters . "melpa-stable")
	(shm . "melpa-stable")
	(smartparens . "melpa-stable")
	(zenburn-theme . "melpa-stable")

	(dash . "melpa-stable")
	(epl . "melpa-stable")
	(pkg-info . "melpa-stable")
	(popup . "melpa-stable")))
